# Generated by Django 4.0.4 on 2022-05-02 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=8, unique=True, verbose_name='Category Code')),
                ('category_title', models.CharField(max_length=128, verbose_name='Category Title')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created On')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated On')),
            ],
            options={
                'ordering': ['category_code'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_code', models.CharField(blank=True, max_length=8, unique=True, verbose_name='Diagnosis Code')),
                ('abbreviated_desc', models.CharField(max_length=256, verbose_name='Abreviated Description')),
                ('full_desc', models.TextField(max_length=512, verbose_name='Full Description')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
    ]
